### ISSUE TITLE
can't import `Pyro` from `pyro`

### ISSUE THREAD

**Issue by zingale** [python-hydro/pyro2#227]
It would be nice to be able to import the `Pyro` class directly from `pyro` as:

```
from pyro import Pyro
```

but this doesn't work if I try adding:

```
from pyro.pyro_sim import Pyro
```

to the `__init__.py`.

I get:

```
ImportError: cannot import name 'Pyro' from 'pyro' (unknown location)
```

**Comment by zingale** [comment]
@yut23 maybe you know what's going on?

**Comment by yut23** [comment]
This works fine for me both in my dev environment (installed with -e) and a clean 3.10 conda-forge environment (installed normally).

**Comment by zingale** [comment]
for me it only works within the `pyro/` directory, but not from somewhere else.  I wonder if that is because we mark `pyro_sim.py` as a script?

**Comment by yut23** [comment]
Probably not, all that does is install a shim into a bin directory somewhere (check `which pyro_sim.py`). Does `from pyro.pyro_sim import Pyro` work from outside the repo directory?

**Comment by zingale** [comment]
yep, that works.

**Comment by yut23** [comment]
Weird. What exactly did you run that gave you the ImportError, and where? Do pyro_sim or Pyro show up if you run `import pyro; print(dir(pyro))` with the extra import in `__init__.py`?

**Comment by zingale** [comment]
I just get:

```

In [1]: import pyro

In [2]: print(dir(pyro))
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Comment by zingale** [comment]
but if I do that from the `pyro2/` directory, I get:

```
['ArrayIndexer',
 'ArrayIndexerFC',
 'BC',
 'CellCenterData2d',
 'FV2d',
 'FaceCenterData2d',
 'Grid2d',
 'Pyro',
 'RKIntegrator',
 'RuntimeParameters',
 'TimerCollection',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_version',
 'mesh',
 'particles',
 'pyro_sim',
 'util',
 'version']
```

**Comment by yut23** [comment]
Looks like something's not installed right, can you run `pip show pyro-hydro`? What are `pyro.__path__` and `pyro.__file__` outside `pyro2/`?

**Comment by zingale** [comment]
this issue was do to a `PYTHONPATH` setting
