### ISSUE TITLE
automate docs building

### ISSUE THREAD

**Issue by zingale** [python-hydro/pyro2#37]
at the moment, the docs live on the `gh-pages` branch, but must be manually pushed.  We should automate the docs build

**Comment by cmsquared** [comment]
Since you are using Travis already, take a look at [doctr](https://github.com/drdoctr/doctr).  I've used this with some success on a project, from within a docker instance on Travis.

**Comment by zingale** [comment]
tat looks neat.  @IanHawke 's RTD solution is nice too.  Maybe it is time to move things there?

**Comment by harpolea** [comment]
Fixed with #40
