### ISSUE TITLE
create a JOSS paper

### ISSUE THREAD

**Issue by zingale** [python-hydro/pyro2#38]
There have been a lot of updates since the original pyro paper, and more importantly, more contributors, so it is a good time for a new pub, this time via JOSS.

**Comment by IanHawke** [comment]
Here's a start on a checklist, based on their [reviewer guidelines](https://joss.theoj.org/about#reviewer_guidelines):

- [ ] The paper itself
- [ X ] Software license
- [ ] Documentation
  - [ ] Statement of need (could argue this is done, but note that JOSS says "Your software should have an obvious research application" where they emphasize "obvious" but here I'd emphasize "research", as the current README statements are about "tutorial" and "self learning")
  - [ ] Installation instructions (should generalize? How much can be done via package management?)
  - [ ] Example usage (a lot of examples included in code: do they cover enough?)
  - [ ] API documentation (check docstring coverage, check "big picture" docs of core classes?)
  - [ ] Auto-build docs (as linked to issue #37), possibly using RTD?
- [ ] Tests (with Travis on unit tests and regression tests could argue this is done)
- [ ] Community guidelines
  - [ ] Contributing guidelines
  - [ ] Report issues or problems (should make this explicit)
  - [ X ] Seek support

**Comment by zingale** [comment]
I'm checking tests -- we have pretty good coverage now.

**Comment by zingale** [comment]
for the research need, I think it is fair to say that this also serves as a platform for prototyping hydro methods, which fills a research need

**Comment by zingale** [comment]
I've added a contributing doc

**Comment by IanHawke** [comment]
Could argue that the contributing doc also covers how to report issues etc, so dealing with the Community guidelines section completely. Could make it fully explicit in the README via eg https://github.com/IanHawke/pyro2/commit/a93f5441351314d6089adfeb5047bac27f31ebc2 .

**Comment by zingale** [comment]
I've started a `paper.md`

**Comment by zingale** [comment]
I think we are pretty much set for the JOSS submission.  I just went through the docs.  There are two unchecked items that we should look at.  We should also formalize in the CONTRIBUTING.md what a significant contribution is, to gain authorship.  We were thinking contributing a solver is an example, in which case we should reach out to the person who contributed the `advection_nonuniform` solver.

**Comment by IanHawke** [comment]
This issue is now complete?
