### ISSUE TITLE
consider migrating from f2py to Cython

### ISSUE THREAD

**Issue by zingale** [python-hydro/pyro2#43]
back when pyro started, there was no cython.  Now we should consider migrating to cython cause it is easier and can be used more easily on some platforms (e.g. Macs)

**Comment by harpolea** [comment]
I tried out using numba instead for the compressible solver and simply using a few @ngit decorators gives a 20-100x speedup for the interface functions (vs plain python) - this might be a nicer alternative to using cython?

**Comment by zingale** [comment]
agreed!

**Comment by harpolea** [comment]
Cool, I've made a `numba` branch and shall see if I can get similar speedups for the other fortran routines

**Comment by zingale** [comment]
we decided on numba instead
