### ISSUE TITLE
add Burgers solver

### ISSUE THREAD

**Issue by zingale** [python-hydro/pyro2#48]
Both viscous and inviscid

**Comment by zhichen3** [comment]
If nobody is working on this, I think I can start with this to help me get familiar with the code.

**Comment by zingale** [comment]
awesome!

**Comment by zingale** [comment]
this was done in #144

**Comment by zhichen3** [comment]
Oh, I thought we also want a viscous version as well.

**Comment by zingale** [comment]
ah indeed!

**Comment by zhichen3** [comment]
Viscous burgers solver was added in #171
