### ISSUE TITLE
"Latest release" on GitHub release page points at 2014 paper version

### ISSUE THREAD

**Issue by ngoldbaum** [python-hydro/pyro2#73]
If you go to https://github.com/python-hydro/pyro2/releases, you'll see that a tag for the version of the code corresponding to the 2014 paper submission is somehow pinned to be prominently displayed in the releases page. Given the new paper and the several releases that have come out since the 2014 paper, you may want to consider adjusting the repository settings so that newer releases are visible without clicking a button on the page.

**Comment by harpolea** [comment]
I think that's because we made a new tag but did not publish it as a release. I've fixed that now.
