### ISSUE TITLE
Setting PYTHONPATH is unnecessary?

### ISSUE THREAD

**Issue by ngoldbaum** [python-hydro/pyro2#74]
It looks like at least the simple advection problem suggested in the readme runs fine on my Python3.7 setup without first setting the `PYTHONPATH` environment variable to point at the `pyro2` directory. Is it still necessary to set that for some other purposes?

**Comment by harpolea** [comment]
If pyro is run from within the main pyro directory, then setting the `PYTHONPATH` environment variable is unnecessary. However, if the pyro module is imported from within a different directory (as it in is in the notebooks in `multigrid/` and `examples/`), then I believe they will not work unless the pyro directory has been added to the python path. 

This would no longer be the case if we made pyro pip-installable, as you suggest in #75

**Comment by ngoldbaum** [comment]
Ah I see. Maybe you want to add a note to the readme and install instructions that setting PYTHONPATH is only necessary if you want to use `pyro` as a module, not if you only use the `pyro.py` script.

**Comment by harpolea** [comment]
Good idea - I've fixed this in 08c7b61f
